name: Update TV Log

on:
  schedule:
    - cron: "0 0 * * *" # Runs every 24 hours at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-tv-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install googleapis@latest

      - name: Debug Working Directory
        run: pwd && ls -R

      - name: Fetch TV Log from Google Sheets
        run: node $(pwd)/scripts/fetch_tv_log.js
        env:
          SHEETS_API_KEY: ${{ vars.SHEETS_API_KEY }}
          TV_SHEET_ID: ${{ secrets.TV_SHEET_ID }}
          
      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/rjkwon/blog.git
          git checkout main  
          git add content/tv/_index.md
          git commit -m "Auto-update TV log from Google Sheets" || exit 0
          git push origin main

      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo -y
      
      - name: Build Hugo Site
        run: hugo --minify
      
      - name: Deploy Hugo Site
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/rjkwon/blog.git
          git add -A
          git commit -m "Rebuild Hugo site with latest TV log" || exit 0
          git push origin main
